import { GameEvaluation } from './analysis.types'
import { classificationLabels, formatEvaluation, formatLoss, moveNumber } from './analysis-formatters'

export type AnalysisFilter = 'all' | 'errors' | 'blunders' | 'white' | 'black'

export function MoveAnalysisList({ evaluations, selectedPly, filter, onFilter, onSelect }: { evaluations: GameEvaluation[]; selectedPly: number | null; filter: AnalysisFilter; onFilter: (filter: AnalysisFilter) => void; onSelect: (item: GameEvaluation) => void }) {
  const visible = evaluations.filter(item => filter === 'all' || (filter === 'errors' && ['inaccuracy', 'mistake', 'blunder'].includes(item.classification ?? '')) || (filter === 'blunders' && item.classification === 'blunder') || (filter === 'white' && item.ply % 2 === 1) || (filter === 'black' && item.ply % 2 === 0))
  return <section className="analysis-panel"><div className="analysis-heading"><div><p className="eyebrow">JUGADAS</p><h3>Evaluación por movimiento</h3></div></div><div className="analysis-filters" role="group" aria-label="Filtrar movimientos">{([['all', 'Todos'], ['errors', 'Errores'], ['blunders', 'Blunders'], ['white', 'Blancas'], ['black', 'Negras']] as const).map(([value, label]) => <button type="button" className={filter === value ? 'active' : ''} onClick={() => onFilter(value)} key={value}>{label}</button>)}</div><div className="analysis-moves">{visible.map(item => <button type="button" className={`analysis-move ${item.classification ?? ''} ${selectedPly === item.ply ? 'selected' : ''}`} onClick={() => onSelect(item)} key={item.id}><span>{moveNumber(item.ply)}</span><strong>{item.played_move_san}</strong><span className="move-classification">{item.classification ? classificationLabels[item.classification] : '—'}</span><span>{formatEvaluation(item.eval_after, item.mate_after, item.score_type)}</span><span>{formatLoss(item.eval_loss)}</span><small>Mejor: {item.best_move_san ?? '—'} · d{item.depth}</small></button>)}</div></section>
}
