import { ChevronLeft, ChevronRight, SkipForward } from 'lucide-react'
import { GameEvaluation } from './analysis.types'
import { classificationLabels, formatEvaluation, formatLoss, isErrorMove, moveNumber } from './analysis-formatters'

export function MoveAnalysisDetail({ evaluations, selected, onSelect }: { evaluations: GameEvaluation[]; selected: GameEvaluation; onSelect: (item: GameEvaluation) => void }) {
  const index = evaluations.findIndex(item => item.id === selected.id)
  const previous = evaluations[index - 1]
  const next = evaluations[index + 1]
  const nextError = evaluations.slice(index + 1).find(isErrorMove)
  const nextBlunder = evaluations.slice(index + 1).find(item => item.classification === 'blunder')
  return <section className="analysis-panel move-analysis-detail"><div className="analysis-heading"><div><p className="eyebrow">DETALLE DE JUGADA</p><h3>{moveNumber(selected.ply)} {selected.played_move_san}</h3></div><span className={`classification-chip ${selected.classification ?? ''}`}>{selected.classification ? classificationLabels[selected.classification] : 'Sin clasificar'}</span></div><div className="move-nav"><button type="button" disabled={!previous} onClick={() => previous && onSelect(previous)} aria-label="Jugada anterior"><ChevronLeft size={16}/>Anterior</button><button type="button" disabled={!next} onClick={() => next && onSelect(next)} aria-label="Jugada siguiente">Siguiente<ChevronRight size={16}/></button><button type="button" disabled={!nextError} onClick={() => nextError && onSelect(nextError)}><SkipForward size={15}/>Siguiente error</button><button type="button" disabled={!nextBlunder} onClick={() => nextBlunder && onSelect(nextBlunder)}><SkipForward size={15}/>Siguiente blunder</button></div><dl className="move-detail-grid"><div><dt>FEN</dt><dd className="fen-value">{selected.fen}</dd></div><div><dt>Jugada realizada</dt><dd>{selected.played_move_san} · {selected.played_move_uci}</dd></div><div><dt>Mejor jugada</dt><dd>{selected.best_move_san ?? '—'}{selected.best_move_uci ? ` · ${selected.best_move_uci}` : ''}</dd></div><div><dt>Evaluación antes / después</dt><dd>{formatEvaluation(selected.eval_before, selected.mate_before, selected.score_type)} → {formatEvaluation(selected.eval_after, selected.mate_after, selected.score_type)}</dd></div><div><dt>Pérdida</dt><dd>{formatLoss(selected.eval_loss)}</dd></div><div><dt>Profundidad / nodos / tiempo</dt><dd>d{selected.depth} · {selected.nodes?.toLocaleString() ?? '—'} · {selected.elapsed_ms ?? '—'} ms</dd></div>{selected.score_type === 'mate' && <div><dt>Mate antes / después</dt><dd>{selected.mate_before ?? '—'} / {selected.mate_after ?? '—'}</dd></div>}<div><dt>Variación principal</dt><dd>{selected.principal_variation ?? 'No disponible'}</dd></div></dl></section>
}
