import { DossierBreakdown, DossierRecord, DossierSummary as DossierSummaryType } from './dossier.types'
import { percent, resultLabel } from './dossier-formatters'

function ResultCard({ label, record }: { label: string; record: DossierRecord }) { return <article className="dossier-result"><span>{label}</span><strong>{record.total_games}</strong><small>{resultLabel(record)} · {percent(record)}% victorias</small></article> }
function Breakdown({ title, items, field }: { title: string; items: DossierBreakdown[]; field: 'platform' | 'speed' }) { return <section className="card dossier-breakdown"><p className="eyebrow">DISTRIBUCIÓN</p><h2>{title}</h2>{items.length ? <div className="dossier-list">{items.map(item => <div key={item[field] ?? 'unknown'}><span>{field === 'speed' && item[field] === 'unknown' ? 'Sin ritmo' : item[field]}</span><b>{item.total_games}</b><small>{resultLabel(item)} · {percent(item)}%</small></div>)}</div> : <p className="subtle-copy">Aún no hay partidas en este rango.</p>}</section> }

export function DossierSummary({ summary }: { summary: DossierSummaryType }) {
  return <><div className="metrics dossier-metrics"><article className="metric"><span className="metric-value">{summary.total_games}</span><span className="metric-label">Partidas reales</span><span className="trend">En el rango seleccionado</span></article><article className="metric"><span className="metric-value">{summary.win_rate}%</span><span className="metric-label">Porcentaje de victoria</span><span className="trend">{resultLabel(summary)}</span></article><article className="metric"><span className="metric-value">{summary.wins}</span><span className="metric-label">Victorias</span><span className="trend">{summary.draws} tablas · {summary.losses} derrotas</span></article></div><section className="card dossier-colors"><p className="eyebrow">POR COLOR</p><h2>Resultados con piezas blancas y negras</h2><div className="dossier-color-grid"><ResultCard label="Blancas" record={summary.white}/><ResultCard label="Negras" record={summary.black}/></div></section><div className="dossier-grid"><Breakdown title="Plataformas" items={summary.platforms} field="platform"/><Breakdown title="Ritmos" items={summary.speeds} field="speed"/></div></>
}
